### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by evansteelepdx** [steelee/Dota2Social#3]
A call to the Steam web API is not made when we login. It does occur when the `isLoggedIn` boolean is set to `true` and there is an entry in the `steamID` part of the redux initialization.

**Comment by evansteelepdx** [comment]
Fixed by fb6f2b05c866100e316c592caa6acc679b122bc4

**Comment by tamnol** [comment]
did you fix this by setting the boolean value to False?
